/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Categoria;
import entidades.CategoriaData;
import entidades.Producto;
import entidades.ProductoData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class ConsultarPorRubro extends javax.swing.JInternalFrame {

    private CategoriaData cd;
    private ProductoData pd;
    private DefaultTableModel modelo;

    /**
     * Creates new form ConsultarPorRubro
     */
    public ConsultarPorRubro() {
        initComponents();
        pd = new ProductoData();
        cd = new CategoriaData();
        modelo = new DefaultTableModel();
        llenarCM();
        llenarCabezera();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbObtenerCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsultaRubro = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(556, 410));

        jLabel1.setText("Listado por rubro");

        jLabel2.setText("Rubro");

        cmbObtenerCategoria.addActionListener(this::cmbObtenerCategoriaActionPerformed);

        tableConsultaRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableConsultaRubro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbObtenerCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbObtenerCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbObtenerCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObtenerCategoriaActionPerformed
        // TODO add your handling code here:        
        llenarTabla();
    }//GEN-LAST:event_cmbObtenerCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Categoria> cmbObtenerCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableConsultaRubro;
    // End of variables declaration//GEN-END:variables

    private void llenarCM() {
        for (Categoria c : cd.obtenerCategoria()) {
            cmbObtenerCategoria.addItem(c);

            cmbObtenerCategoria.setSelectedIndex(0);
        }
    }

    private void llenarCabezera() {
        ArrayList<Object> c = new ArrayList<>();
        c.add("ID");
        c.add("Codigo");
        c.add("Descripcion");
        c.add("Precio");
        c.add("Categoria");
        c.add("Stock");

        for (Object it : c) {
            modelo.addColumn(it);
            tableConsultaRubro.setModel(modelo);

        }
    }

 private void llenarTabla() {

    borrarFila();

    Categoria sel = (Categoria) cmbObtenerCategoria.getSelectedItem();

    if (sel == null) {
        return;
    }

    for (Producto p : pd.obtenerProducto()) {

        if (p.getCategoria().equals(sel)) {

            modelo.addRow(new Object[]{
                p.getIdProducto(),
                p.getCodigo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getCategoria(),
                p.getStock()
            });
        }
    }
}

    private void borrarFila() {
        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
}
