package vistas;

public class Escritorio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Escritorio.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbAdministracion = new javax.swing.JMenu();
        miProducto = new javax.swing.JMenuItem();
        mbConsultaPrecio = new javax.swing.JMenu();
        miConsultarPorNombre = new javax.swing.JMenuItem();
        miConsultarPorPrecio = new javax.swing.JMenuItem();
        miConsultarPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbAdministracion.setText("Administracion");

        miProducto.setText("Producto");
        miProducto.addActionListener(this::miProductoActionPerformed);
        mbAdministracion.add(miProducto);

        jMenuBar1.add(mbAdministracion);

        mbConsultaPrecio.setText("Consultas");

        miConsultarPorNombre.setText("Consulta por Nombre");
        miConsultarPorNombre.addActionListener(this::miConsultarPorNombreActionPerformed);
        mbConsultaPrecio.add(miConsultarPorNombre);

        miConsultarPorPrecio.setText("Consulta por Precio");
        miConsultarPorPrecio.addActionListener(this::miConsultarPorPrecioActionPerformed);
        mbConsultaPrecio.add(miConsultarPorPrecio);

        miConsultarPorRubro.setText("Consulta por Rubro");
        miConsultarPorRubro.addActionListener(this::miConsultarPorRubroActionPerformed);
        mbConsultaPrecio.add(miConsultarPorRubro);

        jMenuBar1.add(mbConsultaPrecio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoActionPerformed
        // TODO add your handling code here:
        GestionDeProducto gestionProducto = new GestionDeProducto();
        gestionProducto.setVisible(true);
        escritorio.add(gestionProducto);
        escritorio.moveToFront(gestionProducto);
    }//GEN-LAST:event_miProductoActionPerformed

    private void miConsultarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarPorNombreActionPerformed
        // TODO add your handling code here:
        ConsultaPorNombre consultaNombre = new ConsultaPorNombre();
        consultaNombre.setVisible(true);
        escritorio.add(consultaNombre);
        escritorio.moveToFront(consultaNombre);
    }//GEN-LAST:event_miConsultarPorNombreActionPerformed

    private void miConsultarPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarPorPrecioActionPerformed
        // TODO add your handling code here:
        ConsultarPorPrecio consultaPrecio = new ConsultarPorPrecio();
        consultaPrecio.setVisible(true);
        escritorio.add(consultaPrecio);
        escritorio.moveToFront(consultaPrecio);
    }//GEN-LAST:event_miConsultarPorPrecioActionPerformed

    private void miConsultarPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarPorRubroActionPerformed
        // TODO add your handling code here:
        ConsultarPorRubro consultaRubro = new ConsultarPorRubro();
        consultaRubro.setVisible(true);
        escritorio.add(consultaRubro);
        escritorio.moveToFront(consultaRubro);
    }//GEN-LAST:event_miConsultarPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Escritorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbAdministracion;
    private javax.swing.JMenu mbConsultaPrecio;
    private javax.swing.JMenuItem miConsultarPorNombre;
    private javax.swing.JMenuItem miConsultarPorPrecio;
    private javax.swing.JMenuItem miConsultarPorRubro;
    private javax.swing.JMenuItem miProducto;
    // End of variables declaration//GEN-END:variables

}
