/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import entidades.Categoria;
import entidades.CategoriaData;
import entidades.Producto;
import entidades.ProductoData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class Escritorio extends javax.swing.JFrame {
    
    private CategoriaData cd;
    private ProductoData pd;
    private DefaultTableModel modelo;
    private Producto productoElegido;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Escritorio.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Escritorio() {
        initComponents();
        pd = new ProductoData();
        cd = new CategoriaData();
        modelo = new DefaultTableModel();
        llenarCM();
        desactivarCampos();
        llenarCabezera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbAdministracion = new javax.swing.JMenu();
        miProducto = new javax.swing.JMenuItem();
        mbConsultaPrecio = new javax.swing.JMenu();
        miConsultarPorNombre = new javax.swing.JMenuItem();
        miConsultarPorPrecio = new javax.swing.JMenuItem();
        miConsultarPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbAdministracion.setText("Administracion");

        miProducto.setText("Producto");
        miProducto.addActionListener(this::miProductoActionPerformed);
        mbAdministracion.add(miProducto);

        jMenuBar1.add(mbAdministracion);

        mbConsultaPrecio.setText("Consultas");

        miConsultarPorNombre.setText("Consulta por Nombre");
        miConsultarPorNombre.addActionListener(this::miConsultarPorNombreActionPerformed);
        mbConsultaPrecio.add(miConsultarPorNombre);

        miConsultarPorPrecio.setText("Consulta por Precio");
        miConsultarPorPrecio.addActionListener(this::miConsultarPorPrecioActionPerformed);
        mbConsultaPrecio.add(miConsultarPorPrecio);

        miConsultarPorRubro.setText("Consulta por Rubro");
        miConsultarPorRubro.addActionListener(this::miConsultarPorRubroActionPerformed);
        mbConsultaPrecio.add(miConsultarPorRubro);

        jMenuBar1.add(mbConsultaPrecio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoActionPerformed
        // TODO add your handling code here:
        GestionDeProducto gestionProducto = new GestionDeProducto();
        gestionProducto.setVisible(true);
        escritorio.add(gestionProducto);
        escritorio.moveToFront(gestionProducto);
    }//GEN-LAST:event_miProductoActionPerformed

    private void miConsultarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarPorNombreActionPerformed
        // TODO add your handling code here:
        ConsultaPorNombre consultaNombre = new ConsultaPorNombre();
        consultaNombre.setVisible(true);
        escritorio.add(consultaNombre);
        escritorio.moveToFront(consultaNombre);
    }//GEN-LAST:event_miConsultarPorNombreActionPerformed

    private void miConsultarPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarPorPrecioActionPerformed
        // TODO add your handling code here:
        ConsultarPorPrecio consultaPrecio = new ConsultarPorPrecio();
        consultaPrecio.setVisible(true);
        escritorio.add(consultaPrecio);
        escritorio.moveToFront(consultaPrecio);
    }//GEN-LAST:event_miConsultarPorPrecioActionPerformed

    private void miConsultarPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarPorRubroActionPerformed
        // TODO add your handling code here:
        ConsultarPorRubro consultaRubro = new ConsultarPorRubro();
        consultaRubro.setVisible(true);
        escritorio.add(consultaRubro);
        escritorio.moveToFront(consultaRubro);
    }//GEN-LAST:event_miConsultarPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Escritorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbAdministracion;
    private javax.swing.JMenu mbConsultaPrecio;
    private javax.swing.JMenuItem miConsultarPorNombre;
    private javax.swing.JMenuItem miConsultarPorPrecio;
    private javax.swing.JMenuItem miConsultarPorRubro;
    private javax.swing.JMenuItem miProducto;
    // End of variables declaration//GEN-END:variables

    private void llenarCM() {
        for (Categoria l : cd.obtenerCategoria()) {
            cmbFiltrarPorCategoria.addItem(l);
            cmbGestionDeProductosCombo.addItem(l);

            cmbFiltrarPorCategoria.setSelectedIndex(-1);
        }
    }

    private void activarCampos() {
        txtGestionDeProductosCodigo.setEnabled(true);
        txtGestionDeProductosDescripcion.setEnabled(true);
        txtGestionDeProductosPrecio.setEnabled(true);
        spnGestionDeProductos.setEnabled(true);
        cmbGestionDeProductosCombo.setEnabled(true);
    }

    private void desactivarCampos() {
        txtGestionDeProductosCodigo.setEnabled(false);
        txtGestionDeProductosDescripcion.setEnabled(false);
        txtGestionDeProductosPrecio.setEnabled(false);
        spnGestionDeProductos.setEnabled(false);
        cmbGestionDeProductosCombo.setEnabled(false);
    }

    private void limpiarCampos() {
        txtGestionDeProductosCodigo.setText("");
        txtGestionDeProductosDescripcion.setText("");
        txtGestionDeProductosPrecio.setText("");
        cmbGestionDeProductosCombo.setSelectedIndex(-1);
        spnGestionDeProductos.setValue(0);
    }

    private void llenarCabezera() {
        ArrayList<Object> c = new ArrayList<>();
        c.add("ID");
        c.add("Codigo");
        c.add("Descripcion");
        c.add("Precio");
        c.add("Categoria");
        c.add("Stock");

        for (Object it : c) {
            modelo.addColumn(it);
            tblGestionDeProductos.setModel(modelo);

        }
    }

    private void llenarTabla() {

        borrarFila();
        Categoria sel = (Categoria) cmbFiltrarPorCategoria.getSelectedItem();

        if (sel != null) {
            for (Producto p : pd.obtenerProducto()) {

                if (p.getCategoria().equals(sel)) {

                    modelo.addRow(new Object[]{p.getIdProducto(), p.getCodigo(), p.getDescripcion(), p.getPrecio(), p.getCategoria(), p.getStock()});
                }
            }
        }
    }

    private void borrarFila() {
        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
}

